# Bridge ethernet to containers
network:
  version: 2
  renderer: networkd

  ethernets:
    enp3s0:
      dhcp4: false
      dhcp6: false

  bridges:
    br0:
      dhcp4: true
      interfaces:
        - enp3s0
      nameservers:
        addresses:
          - 192.168.0.127
