# Bridge ethernet to containers
network:
  version: 2
  renderer: networkd

  ethernets:
    enp2s0:
      dhcp4: false
      dhcp6: false

  bridges:
    br0:
      dhcp4: true
      interfaces:
        - enp2s0
      routes:
        - to: default
          via: 192.168.0.1
      nameservers:
        addresses:
          - 192.168.0.127
      parameters:
        stp: true
        forward-delay: 4
